[toolchain]
anchor_version = "0.29.0"

[features]
skip-lint = false

[programs.devnet]
nft_minting = "44mKazm9XGzWedW2x3KGXmRMAGkbU15pFNVKokL6ERg9"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
