[package]
name = "nft-minting"
version = "0.1.0"
authors = ["Your Name <youremail@example.com>"]
edition = "2018"

[dependencies]
solana-program = "1.10.32"
mpl-token-metadata = "1.2.0"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3